[package]
name = "miden"
description = "Miden SDK"
version = "0.9.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
miden-sdk-alloc = { version = "0.9.0", path = "../alloc" }
miden-stdlib-sys = { version = "0.9.0", path = "../stdlib-sys" }
miden-base = { version = "0.9.0", path = "../base" }
miden-base-macros = { version = "0.9.0", path = "../base-macros" }
miden-base-sys = { version = "0.9.0", path = "../base-sys" }
miden-field-repr = { version = "0.9.0", path = "../field-repr/repr" }
miden-field.workspace = true
wit-bindgen = { version = "0.46", default-features = false, features = ["macros"] }

[features]
default = []
