[package]
name = "miden-stdlib-sys"
description = "Low-level Rust bindings for the Miden standard library"
version = "0.9.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
build = "build.rs"
links = "miden_stdlib_sys_stubs"

[lib]
crate-type = ["rlib"]

[dependencies]
miden-field.workspace = true

[features]
default = []
