[package]
name = "miden-field-repr-tests"
description = "Integration tests for felt representation serialization/deserialization"
version = "0.9.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish = false

[dependencies]
miden-field.workspace = true
miden-field-repr = { path = "../repr", version = "0.9.0" }
miden-core.workspace = true

[dev-dependencies]
p3-field = { version = "0.4.2", default-features = false }
miden-integration-tests = { path = "../../../tests/integration" }
midenc-frontend-wasm.workspace = true
midenc-session.workspace = true
midenc-expect-test.workspace = true
miden-debug.workspace = true
miden-protocol.workspace = true
miden-processor.workspace = true
